export const data = [
  {
    id: 1,
    name: 'White Blood Cells (WBCs)',
    description: 'Number of white blood cells per volume of blood',
    unit: '/μL',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 4000,
    maximum: 11000,
  },
  {
    id: 2,
    name: 'Red Blood Cells (RBCs)',
    description: 'Number of red blood cells per volume of blood',
    unit: '/μL',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 4.2,
    maximum: 5.9,
  },
  {
    id: 3,
    name: 'Hemoglobin (Hb)',
    description: 'Concentration of hemoglobin in the blood',
    unit: 'g/dL',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 13.2,
    maximum: 17.3,
  },
  {
    id: 4,
    name: 'Platelets',
    description: 'Number of platelets per volume of blood',
    unit: '/μL',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 150000,
    maximum: 450000,
  },
  {
    id: 5,
    name: 'Absolute Neutrophil Count (ANC)',
    description: 'Number of neutrophils per volume of blood',
    unit: '/μL',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 1500,
    maximum: 8000,
  },
  {
    id: 6,
    name: 'Prothrombin Time (PT)',
    description: 'Time it takes for blood to clot',
    unit: 'seconds',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 11,
    maximum: 13,
  },
  {
    id: 7,
    name: 'Activated Partial Thromboplastin Time (aPTT)',
    description: 'Time it takes for blood to clot with specific activators',
    unit: 'seconds',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 25,
    maximum: 35,
  },
  {
    id: 8,
    name: 'Alanine Aminotransferase (ALT)',
    description: 'Enzyme found predominantly in the liver',
    unit: 'IU/L',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 7,
    maximum: 56,
  },
  {
    id: 9,
    name: 'Aspartate Aminotransferase (AST)',
    description:
      'Enzyme found in various tissues including the liver and heart',
    unit: 'IU/L',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 5,
    maximum: 40,
  },
  {
    id: 10,
    name: 'Bilirubin',
    description: 'Yellow pigment formed by the breakdown of red blood cells',
    unit: 'mg/dL',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 0.2,
    maximum: 1.2,
  },
  {
    id: 11,
    name: 'Blood Urea Nitrogen (BUN)',
    description: 'Measure of urea nitrogen in the blood',
    unit: 'mg/dL',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 7,
    maximum: 20,
  },
  {
    id: 12,
    name: 'Creatinine',
    description: 'Waste product produced by muscles',
    unit: 'mg/dL',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 0.6,
    maximum: 1.3,
  },
  {
    id: 13,
    name: 'Glucose',
    description: 'Sugar present in the blood',
    unit: 'mg/dL',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 70,
    maximum: 100,
  },
  {
    id: 14,
    name: 'Calcium',
    description: 'Mineral important for bone health and other functions',
    unit: 'mg/dL',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 8.5,
    maximum: 10.5,
  },
  {
    id: 15,
    name: 'Potassium',
    description: 'Electrolyte essential for nerve and muscle function',
    unit: 'mEq/L',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 3.5,
    maximum: 5.0,
  },
  {
    id: 16,
    name: 'Sodium',
    description: 'Electrolyte important for fluid balance and nerve function',
    unit: 'mEq/L',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 135,
    maximum: 145,
  },
  {
    id: 17,
    name: 'Magnesium',
    description: 'Mineral involved in hundreds of biochemical reactions',
    unit: 'mg/dL',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 1.5,
    maximum: 2.5,
  },
  {
    id: 18,
    name: 'Phosphate',
    description: 'Mineral important for bone health and energy metabolism',
    unit: 'mg/dL',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 2.5,
    maximum: 4.5,
  },
  {
    id: 19,
    name: 'Lactate Dehydrogenase (LDH)',
    description: 'Enzyme found in many body tissues',
    unit: 'IU/L',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 140,
    maximum: 280,
  },
  {
    id: 20,
    name: 'C-Reactive Protein (CRP)',
    description: 'Marker of inflammation in the body',
    unit: 'mg/L',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 0,
    maximum: 3,
  },
  {
    id: 21,
    name: 'Ferritin',
    description: 'Protein that stores iron in the body',
    unit: 'ng/mL',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 30,
    maximum: 400,
  },
  {
    id: 22,
    name: 'Total Protein',
    description: 'Measure of total protein concentration in the blood',
    unit: 'g/dL',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 6,
    maximum: 8,
  },
  {
    id: 23,
    name: 'Albumin',
    description: 'Protein made by the liver',
    unit: 'g/dL',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 3.5,
    maximum: 5.0,
  },
  {
    id: 24,
    name: 'Globulin',
    description: 'Group of proteins made by the liver and immune system',
    unit: 'g/dL',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 2,
    maximum: 3.5,
  },
  {
    id: 25,
    name: 'Total Bilirubin',
    description: 'Measure of total bilirubin in the blood',
    unit: 'mg/dL',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 0.3,
    maximum: 1.2,
  },
  {
    id: 26,
    name: 'Thyroid Stimulating Hormone (TSH)',
    description:
      'Hormone produced by the pituitary gland that stimulates the thyroid gland',
    unit: 'μIU/mL',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 0.4,
    maximum: 4,
  },
  {
    id: 27,
    name: 'Free Thyroxine (FT4)',
    description: 'Unbound form of the thyroid hormone thyroxine',
    unit: 'ng/dL',
    createdAt: '2024-03-19T00:00:00Z',
    minimum: 0.8,
    maximum: 1.8,
  },
];
