import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';

import './globals.css';
import 'simplebar-react/dist/simplebar.min.css';

import Providers from '@/components/Providers';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen bg-background', inter.className)}>
        <Providers>
          <NextTopLoader color="#2563eb" />
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
