import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';

import './globals.css';
import 'simplebar-react/dist/simplebar.min.css';

import Providers from '@/components/Providers';
import Sidebar from '@/components/Sidebar';
import Navbar from '@/components/Navbar';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('min-h-screen bg-background', inter.className)}>
        <Providers>
          <NextTopLoader color="#2563eb" />
          {modal}
          <div className="h-full">
            <Navbar />
            <div className="fixed inset-y-0 mt-16 hidden w-16 flex-col md:flex">
              <Sidebar />
            </div>
            <main className="h-full pt-16 md:pl-16">
              <div className="h-full space-y-2 px-4">{children}</div>
            </main>
          </div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
