import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from '@/components/Providers';
import { cn } from '@/lib/utils';
import Sidebar from '@/components/Sidebar';
import Navbar from '@/components/Navbar';
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('bg-background', inter.className)}>
        <Providers>
          <NextTopLoader color="#2563eb" />
          <div className="h-full">
            <Navbar />
            <div className="hidden md:flex mt-16 w-16 flex-col fixed inset-y-0">
              <Sidebar />
            </div>
            <main className="pt-16 h-full md:pl-16">
              <div className="h-full p-4 space-y-2">{children}</div>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
